
#' ## Function to do a linear regression of K functions
#'

#' @param formula A one-sided formula describing the model to be fit, following
#' @param k A list of Kfunctions.
#' @param data The covariates.
#' @param weights The weights vector, probably generated by KfuncWeightsCalc.
#' the lme4 syntax. See \code{\link[lme4]{lmer}}
#' @param na.action How to deal with missing values.
#' See \code{\link[stats]{na.action}}
#' 
#' @return An object of class kfunclmer.
#'
#' @export
#'



klm_i <- function(formula, k, data, weights){
  weights <- weights/mean(weights)
  k_dataframe <- data.frame(k=k, data, weights = weights) # make data frame
  
  k_data.frame <- data.frame(k=k, data, weights=weights) ## extract data
  ## add K to lhs of formula
  formula <-  stats::update(formula, k~.)
  
  ## fit model 
  lm_ki <- eval(substitute(lm(formula, data=k_data.frame, weights=weights,
                            x=T, y=T), list(formula = formula,
                                            k_dataframe=k_dataframe)))
  return(lm_ki)
}