
#' function to fit mixed effects model to k functions at a set distance
#'
#'@import lme4
#'
#' @param formula A one-sided formula describing the model to be fit, following
#' @param k A list of Kfunctions.
#' @param data The covariates.
#' @param weights The weights vector, probably generated by KfuncWeightsCalc.
#' the lme4 syntax. See \code{\link[lme4]{lmer}}
#' @param na.action How to deal with missing values.
#' See \code{\link[stats]{na.action}}
#' @param ... Other arguments to \code{\link[lme4]{lmer}}
#' @return An object of class kfunclmer.
#'
#' @export
#'
#' @examples
#'
#' library(spatstat)
#' pppx <- replicate(50, rpoispp(runif(1, 10, 100)), simplify=FALSE)
#' r <- seq(0, 0.25, 0.05)
#' k <- lapply(pppx, Kest, r=r, correction='border')
#' k <- sapply(k, function(x) x[['border']][2])
#' weights <- lapply(pppx, kfuncWeightsCalc, r=r,
#' correction="border", type="nx_A")
#' weights <- sapply(weights, function(x) x[[2]])
#' dat <- data.frame(x=runif(50, 0, 10), gr = sample(1:10, 50, replace=TRUE))
#' formula = ~ x + (1|gr)
#' klmer(~x + (1|gr), k=k, data=dat, weights=weights)

klmer <- function(formula, k, data, weights, na.action="na.omit", ...)
{

  ## also need to make sure these weights have a mean of 1
  weights <- weights/mean(weights)

  ###require(nlme) ## load required packages
  k_dataframe <- data.frame(k=k, data, weights = weights) # make data frame


  ## add K to lhs of formula
  formula <-  stats::update(formula, k~.)

  ## Fit model using 'try' to avoid problems of non-convergence at some
  ## distances
  lmer_ki <- try(lmer(formula, k_dataframe, weights=weights,
         na.action=na.action, ...),silent=T)

  if(class(lmer_ki) =='try-error')
    lmer_ki <- NULL
  return(lmer_ki)
}
